project_id = "rglaszkaqbagpbtursjf"

[functions.verify-certification]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.delete_user_admin]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
